- 👋 Hi, I’m @Praveenkushinpi
- 👀 I’m interested in coding and art, especially mangas
- 🌱 I’m currently learning to code  on Java too
- 💞️ I’m looking to collaborate on .....
- 📫 How to reach me ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

<!---
Praveenkushinpi/Praveenkushinpi is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
